### ISSUE TITLE
[BUG] "This interaction failed" for Button Interactions

### ISSUE THREAD

**Issue by Hedreon** [DynxstyGIT/DIH4JDA#104]
**Describe the bug**
Even though I ❤️ DIH4JDA, it sometimes has it's own problems so, no matter how the code is written, either copying from the `TestCommand()` [example](https://javadoc.io/static/xyz.dynxsty/dih4jda/1.6.2/xyz/dynxsty/dih4jda/interactions/components/ButtonHandler.html#handleButton(net.dv8tion.jda.api.events.interaction.component.ButtonInteractionEvent,net.dv8tion.jda.api.interactions.components.buttons.Button)) or MIY (**M**aking **I**t **Y**ourself) from scratch, it will always fail to respond and just keep saying "This interaction failed"

**To Reproduce**
1. Copy `TestCommand()` [example](https://javadoc.io/static/xyz.dynxsty/dih4jda/1.6.2/xyz/dynxsty/dih4jda/interactions/components/ButtonHandler.html#handleButton(net.dv8tion.jda.api.events.interaction.component.ButtonInteractionEvent,net.dv8tion.jda.api.interactions.components.buttons.Button)) into your empty java class
2. Run bot
3. Click on either one of the two buttons
4. "This interaction failed"

**Expected behavior**
What is supposed to happen is that the bot will successfully respond to the `TestCommand()` [example.](https://javadoc.io/static/xyz.dynxsty/dih4jda/1.6.2/xyz/dynxsty/dih4jda/interactions/components/ButtonHandler.html#handleButton(net.dv8tion.jda.api.events.interaction.component.ButtonInteractionEvent,net.dv8tion.jda.api.interactions.components.buttons.Button)) Normally, if you click on the "Click me!" button, the bot will respond with "Thanks for not clicking the other button! :)" or if you click on the "NO! Click me!" button, the bot will respond with "Phew, thanks for clicking me..."

**Additional context**
None.

**Comment by Hedreon** [comment]
Or I maybe doin' DIH4JDA wrong

**Comment by DenuxPlays** [comment]
Can you add this:
```java
dih4JDA.addButtonMappings(IdMapping.of(new TestCommand(), "test-button"));
```
where you initialize DIH4JDA please?

**Comment by Hedreon** [comment]
> Can you add this:
> 
> ```java
> dih4JDA.addButtonMappings(IdMapping.of(new TestCommand(), "test-button"));
> ```
> 
> where you initialize DIH4JDA please?

Thanks. Here's a suggestion: Add something that tells the reader to add button mapping for this to work

**Comment by DynxstyGIT** [comment]
I even thought about turning this into an annotation instead, as the current thingy is quite ugly tbh

**Comment by Hedreon** [comment]
> I even thought about turning this into an annotation instead, as the current thingy is quite ugly tbh

please include it into the same `TestCommand()` code block if you are going to turn this into an annotation.
