### ISSUE TITLE
Add JitPack repository to README installation section or publish to maven central

### ISSUE THREAD

**Issue by danthe1st** [DynxstyGIT/DIH4JDA#11]
The installation section of the `README.md` mentions importing DIH4JDA like this:

> ```xml
> <dependency> 
>     <groupId>com.github.DynxstyGIT</groupId> 
>     <artifactId>DIH4JDA</artifactId> 
>     <version>${DIH4JDA_VERSION}</version> 
> </dependency>
> ```

However, this only works if the jitpack repository is added to the `pom.xml`.

The Jitpack repository can be added to the `pom.xml` like the following:
```xml
<repositories>
	<repository>
	    <id>jitpack.io</id>
	    <url>https://jitpack.io</url>
	</repository>
</repositories>
```
For Gradle projects, the following configuration is required:
```gradle
allprojects {
	repositories {
		maven { url 'https://jitpack.io' }
	}
}
```

This is also explained [on JitPack](https://jitpack.io/#DynxstyGIT/DIH4JDA).

Alternatively, the project can also be published on [Maven Central](https://repo1.maven.org). See [this](https://central.sonatype.org/publish/publish-guide/#create-a-ticket-with-sonatype) for more details on publishing to Maven Central.

**Comment by DenuxPlays** [comment]
For gradle its cleaner to add the jitpack repository like this.
 
```gradle
 
 ​repositories​ { 
 ​    mavenCentral()  
 ​    maven { url ​'​https://jitpack.io​'​ } 
 ​}

```
